Repository jenkinsci/jenkins-test-harness-htmlunit, pull requests merged in 2023-01, with the labels that each got.

#96 Revert "Bump htmlunit from 2.67.0 to 2.68.0"
  pom.xml
Labels: bug, dependencies

#100 Upgrade HtmlUnit from 2.67.0 to 2.70.0
  pom.xml
Labels: dependencies, java

#102 Clean up shading configuration
  pom.xml
Labels: internal
